# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the bin/rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

# 全権削除
Classroom.delete_all
Teacher.delete_all
Student.delete_all
Situation.delete_all
Attendance.delete_all


# クラス
c11 = Classroom.create(grade: 1, number: 1, name: "１年１組")
c12 = Classroom.create(grade: 1, number: 2, name: "１年２組")
c13 = Classroom.create(grade: 1, number: 3, name: "１年３組")
c14 = Classroom.create(grade: 1, number: 4, name: "１年４組")
c21 = Classroom.create(grade: 2, number: 1, name: "２年１組")
c22 = Classroom.create(grade: 2, number: 2, name: "２年２組")
c23 = Classroom.create(grade: 2, number: 3, name: "２年３組")
c24 = Classroom.create(grade: 2, number: 4, name: "２年４組")
c31 = Classroom.create(grade: 3, number: 1, name: "３年１組")
c32 = Classroom.create(grade: 3, number: 2, name: "３年２組")
c33 = Classroom.create(grade: 3, number: 3, name: "３年３組")
c34 = Classroom.create(grade: 3, number: 4, name: "３年４組")


# 先生
Teacher.create(teacher_id: "14nagata", password: "14", name: "永田亮", kanri: false,  classroom_id: c14.id)
Teacher.create(teacher_id: "24yoshida", password: "24", name: "吉田利幸", kanri: false,  classroom_id: c24.id)
Teacher.create(teacher_id: "34sato", password: "34", name: "佐藤魁人", kanri: false,  classroom_id: c34.id)
Teacher.create(teacher_id: "00kotyo", password: "00", name: "水津則義", kanri: false, classroom_id: nil)
Teacher.create(teacher_id: "01tunoori", password: "01", name: "角折義男", kanri: false, classroom_id: nil)
Teacher.create(teacher_id: "55hoken", password: "55", name: "齋藤果歩", kanri: false, classroom_id: nil)

# 生徒
# 一年四組
s1401 = Student.create(name: "赤木 桃愛", classroom_id: c14.id, number: 1)
s1402 = Student.create(name: "吾郷 璃奈", classroom_id: c14.id, number: 2)
s1403 = Student.create(name: "足立 侑鈴子", classroom_id: c14.id, number: 3)
s1404 = Student.create(name: "伊藤 寛気", classroom_id: c14.id, number: 4)
s1405 = Student.create(name: "今岡 里菜", classroom_id: c14.id, number: 5)
s1406 = Student.create(name: "岩﨑 翔洋", classroom_id: c14.id, number: 6)
s1407 = Student.create(name: "内田 芙佳", classroom_id: c14.id, number: 7)
s1408 = Student.create(name: "漆谷 空楓", classroom_id: c14.id, number: 8)
s1409 = Student.create(name: "太田 陽菜", classroom_id: c14.id, number: 9)
s1410 = Student.create(name: "沖津 右典", classroom_id: c14.id, number: 10)
s1411 = Student.create(name: "梶谷 悠真", classroom_id: c14.id, number: 11)
s1412 = Student.create(name: "勝部 滉大", classroom_id: c14.id, number: 12)
s1413 = Student.create(name: "勝部 蒼大", classroom_id: c14.id, number: 13)
s1414 = Student.create(name: "加藤 壱成", classroom_id: c14.id, number: 14)
s1415 = Student.create(name: "木谷 海來", classroom_id: c14.id, number: 15)
s1416 = Student.create(name: "木村 康佑", classroom_id: c14.id, number: 16)
s1417 = Student.create(name: "佐藤 璃空", classroom_id: c14.id, number: 17)
s1418 = Student.create(name: "杉原 輝星", classroom_id: c14.id, number: 18)
s1419 = Student.create(name: "園山 絵虹", classroom_id: c14.id, number: 19)
s1420 = Student.create(name: "竹下 真帆", classroom_id: c14.id, number: 20)
s1421 = Student.create(name: "武田 隼翔", classroom_id: c14.id, number: 21)
s1422 = Student.create(name: "竹中 陽日", classroom_id: c14.id, number: 22)
s1423 = Student.create(name: "出川 瑛士", classroom_id: c14.id, number: 23)
s1424 = Student.create(name: "寺本 大輝", classroom_id: c14.id, number: 24)
s1425 = Student.create(name: "富田 梓", classroom_id: c14.id, number: 25)
s1426 = Student.create(name: "中尾 勇翔", classroom_id: c14.id, number: 26)
s1427 = Student.create(name: "錦織 心結", classroom_id: c14.id, number: 27)
s1428 = Student.create(name: "濵村 ひかり", classroom_id: c14.id, number: 28)
s1429 = Student.create(name: "藤原 大和", classroom_id: c14.id, number: 29)
s1430 = Student.create(name: "松島 英翔", classroom_id: c14.id, number: 30)
s1431 = Student.create(name: "目良 流星", classroom_id: c14.id, number: 31)
s1432 = Student.create(name: "森山 舜", classroom_id: c14.id, number: 32)
s1433 = Student.create(name: "森脇 敦紫", classroom_id: c14.id, number: 33)
s1434 = Student.create(name: "矢田 悠真", classroom_id: c14.id, number: 34)
s1435 = Student.create(name: "山側 真由奈", classroom_id: c14.id, number: 35)
s1436 = Student.create(name: "山本 遥斗", classroom_id: c14.id, number: 36)
s1437 = Student.create(name: "渡部 大翔", classroom_id: c14.id, number: 37)
# 二年四組
s2401 = Student.create(name: "安達 康浩", classroom_id: c24.id, number: 1)
s2402 = Student.create(name: "石田 健人", classroom_id: c24.id, number: 2)
s2403 = Student.create(name: "和泉 海音", classroom_id: c24.id, number: 3)
s2404 = Student.create(name: "伊藤 颯人", classroom_id: c24.id, number: 4)
s2405 = Student.create(name: "井上 優弥", classroom_id: c24.id, number: 5)
s2406 = Student.create(name: "岩成 歩", classroom_id: c24.id, number: 6)
s2407 = Student.create(name: "江角 花音", classroom_id: c24.id, number: 7)
s2408 = Student.create(name: "大坂 樹輝", classroom_id: c24.id, number: 8)
s2409 = Student.create(name: "恩田 理央", classroom_id: c24.id, number: 9)
s2410 = Student.create(name: "川瀨 啓太", classroom_id: c24.id, number: 10)
s2411 = Student.create(name: "黒田 千介", classroom_id: c24.id, number: 11)
s2412 = Student.create(name: "小谷 大耀", classroom_id: c24.id, number: 12)
s2413 = Student.create(name: "兒玉 玲", classroom_id: c24.id, number: 13)
s2414 = Student.create(name: "小松原 晴輝", classroom_id: c24.id, number: 14)
s2415 = Student.create(name: "坂本 秀太", classroom_id: c24.id, number: 15)
s2416 = Student.create(name: "坂本 智香", classroom_id: c24.id, number: 16)
s2417 = Student.create(name: "櫻井 咲希", classroom_id: c24.id, number: 17)
s2418 = Student.create(name: "佐藤 那生", classroom_id: c24.id, number: 18)
s2419 = Student.create(name: "陶山 巧充", classroom_id: c24.id, number: 19)
s2420 = Student.create(name: "瀨崎 那琉", classroom_id: c24.id, number: 20)
s2421 = Student.create(name: "妹尾 なつみ", classroom_id: c24.id, number: 21)
s2422 = Student.create(name: "高橋 和冶", classroom_id: c24.id, number: 22)
s2423 = Student.create(name: "谷村 美結", classroom_id: c24.id, number: 23)
s2424 = Student.create(name: "成相 沫音", classroom_id: c24.id, number: 24)
s2425 = Student.create(name: "服部 愛莉", classroom_id: c24.id, number: 25)
s2426 = Student.create(name: "藤田 結衣", classroom_id: c24.id, number: 26)
s2427 = Student.create(name: "古川 奈々", classroom_id: c24.id, number: 27)
s2428 = Student.create(name: "槇原 啓太", classroom_id: c24.id, number: 28)
s2429 = Student.create(name: "槇原 凛", classroom_id: c24.id, number: 29)
s2430 = Student.create(name: "松野 涼太", classroom_id: c24.id, number: 30)
s2431 = Student.create(name: "三上 泰由", classroom_id: c24.id, number: 31)
s2432 = Student.create(name: "三﨑 蕾希", classroom_id: c24.id, number: 32)
s2433 = Student.create(name: "水原 彩葉", classroom_id: c24.id, number: 33)
s2434 = Student.create(name: "森山 あかり", classroom_id: c24.id, number: 34)
s2435 = Student.create(name: "森脇 くれは", classroom_id: c24.id, number: 35)
s2436 = Student.create(name: "矢田 悠斗", classroom_id: c24.id, number: 36)
s2437 = Student.create(name: "山崎 颯斗", classroom_id: c24.id, number: 37)
s2438 = Student.create(name: "山下 知夏", classroom_id: c24.id, number: 38)
s2439 = Student.create(name: "山本 璃果", classroom_id: c24.id, number: 39)
s2440 = Student.create(name: "和田 彩優花", classroom_id: c24.id, number: 40)
# 三年四組
s3401 = Student.create(name: "吾郷 拓海", classroom_id: c34.id, number: 1)
s3402 = Student.create(name: "麻布 咲穂", classroom_id: c34.id, number: 2)
s3403 = Student.create(name: "糸賀 裕人", classroom_id: c34.id, number: 3)
s3404 = Student.create(name: "岩成 織姫", classroom_id: c34.id, number: 4)
s3405 = Student.create(name: "上村 花", classroom_id: c34.id, number: 5)
s3406 = Student.create(name: "内部 功希", classroom_id: c34.id, number: 6)
s3407 = Student.create(name: "大野 玲也", classroom_id: c34.id, number: 7)
s3408 = Student.create(name: "小村 彩", classroom_id: c34.id, number: 8)
s3409 = Student.create(name: "北村 優", classroom_id: c34.id, number: 9)
s3410 = Student.create(name: "桐原 空", classroom_id: c34.id, number: 10)
s3411 = Student.create(name: "久保 大和", classroom_id: c34.id, number: 11)
s3412 = Student.create(name: "黒田 雅斗", classroom_id: c34.id, number: 12)
s3413 = Student.create(name: "桑原 海斗", classroom_id: c34.id, number: 13)
s3414 = Student.create(name: "後長 壱咲", classroom_id: c34.id, number: 14)
s3415 = Student.create(name: "小林 颯真", classroom_id: c34.id, number: 15)
s3416 = Student.create(name: "佐藤 政翔", classroom_id: c34.id, number: 16)
s3417 = Student.create(name: "高木 柊人", classroom_id: c34.id, number: 17)
s3418 = Student.create(name: "高橋 孝明", classroom_id: c34.id, number: 18)
s3419 = Student.create(name: "竹田 煌介", classroom_id: c34.id, number: 19)
s3420 = Student.create(name: "常松 咲来", classroom_id: c34.id, number: 20)
s3421 = Student.create(name: "富田 美咲", classroom_id: c34.id, number: 21)
s3422 = Student.create(name: "永見 遼空", classroom_id: c34.id, number: 22)
s3423 = Student.create(name: "南場 翔太", classroom_id: c34.id, number: 23)
s3424 = Student.create(name: "野津 悠", classroom_id: c34.id, number: 24)
s3425 = Student.create(name: "原 楓喜", classroom_id: c34.id, number: 25)
s3426 = Student.create(name: "福島 大樹", classroom_id: c34.id, number: 26)
s3427 = Student.create(name: "本間 紫雲", classroom_id: c34.id, number: 27)
s3428 = Student.create(name: "本間 菜月", classroom_id: c34.id, number: 28)
s3429 = Student.create(name: "松本 佳衣斗", classroom_id: c34.id, number: 29)
s3430 = Student.create(name: "三代 嵩希琉", classroom_id: c34.id, number: 30)
s3431 = Student.create(name: "森山 洋介", classroom_id: c34.id, number: 31)
s3432 = Student.create(name: "山根 采華", classroom_id: c34.id, number: 32)
s3433 = Student.create(name: "米山 遥人", classroom_id: c34.id, number: 33)
s3434 = Student.create(name: "渡邊 虎徳", classroom_id: c34.id, number: 34)


# 出欠区分
s_kesseki = Situation.create(name: "欠席")
s_syuttei = Situation.create(name: "出席停止")
s_chikoku = Situation.create(name: "遅刻")
s_soutai = Situation.create(name: "早退")
s_fumei = Situation.create(name: "不明")

# 出欠情報
#base_date = Date.today
base_date = Time.local(2024, 2, 7)
Attendance.create(date: base_date,     student_id: s3402.id, situation_id: s_kesseki.id, reason: "体調不良", period_start: nil, period_end: nil, comment: "37.5", teacher_id: nil)
Attendance.create(date: base_date, student_id: s3404.id, situation_id: s_fumei.id, reason: nil, period_start: nil, period_end: nil, comment: nil, teacher_id: nil)
Attendance.create(date: base_date - 1, student_id: s3405.id, situation_id: s_chikoku.id, reason: "寝坊", period_start: nil, period_end: nil, comment: nil, teacher_id: nil)
Attendance.create(date: base_date,     student_id: s3430.id, situation_id: s_syuttei.id, reason: "インフル", period_start: base_date - 1, period_end: base_date + 2, comment: "38.7", teacher_id: nil)
